development:
  adapter: mysql2
  database: ang-user-dev
  host: localhost
  username: root
  password: root

test:
  adapter: mysql2
  database: ang-user-test
  host: localhost
  username: root
  password: root

production:
  adapter: mysql2
  database: ang-user-production
  host: localhost
  username: root
  password: root